---
- name: Create UCS Service Profile Template
  hosts: ucs-sim
  connection: local
  gather_facts: no

  tasks:
    - name: Create UCS MAC pool 
      ucs_mac_pool:
        ucsm_ip={{ inventory_hostname }}
        ucsm_user="admin"
        ucsm_pw="admin"
        state="absent"
        pool_name="test-pool-ansible"
        pool_desc="test pool desc"
        start_range="00:25:B5:FA:FA:00"
        end_range="00:25:B5:FA:FA:FF"
    
    - name: Create UCS UUID pool 
      ucs_uuid_pool:
        ucsm_ip={{ inventory_hostname }}
        ucsm_user="admin"
        ucsm_pw="admin"
        state="absent"
        pool_name="test-pool-ansible"
        pool_desc="test pool desc"
        start_range="0000-0025B5001101"
        end_range="0000-0025B50011FF"
    
    - name: Create UCS WWPN Pool
      ucs_wwpn_pool:
        ucsm_ip={{ inventory_hostname }}
        ucsm_user="admin"
        ucsm_pw="admin"
        state="absent"
        pool_name="test-pool-ansible"
        pool_desc="test pool desc"
        start_range="20:00:00:25:B5:FA:FA:00"
        end_range="20:00:00:25:B5:FA:FA:FF"
    
    - name: Create UCS WWNN Pool
      ucs_wwnn_pool:
        ucsm_ip={{ inventory_hostname }}
        ucsm_user="admin"
        ucsm_pw="admin"
        state="absent"
        pool_name="test-wwnn-ansible"
        pool_desc="test pool desc"
        start_range="20:00:00:25:B5:F0:FA:00"
        end_range="20:00:00:25:B5:F0:FA:FF"
    
    - name: Create UCS Server Pool
      ucs_server_pool:
        ucsm_ip={{ inventory_hostname }}
        ucsm_user="admin"
        ucsm_pw="admin"
        state="absent"
        pool_name="test-svr-ansible"
        pool_desc="test pool desc"
        chassis_range="2,3,5"
        slot_range="1,3,5,7"

